version: '3.9'
services:
  db:
    image: postgres:15.1-alpine
    container_name: db
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ctf"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CTF
    env_file: ./.env
    command: ['/CTF/docker/app.sh']
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
    driver: local
