version: '3.9'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CTF
    env_file: .env
    command: ['/CTF/docker/app.sh']
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_data:
    driver: local
