version: '3.7'

services:
  db:
      image: postgres:15.1-alpine
      container_name: db
      env_file: .env
      volumes: [postgres_data:/var/lib/postgresql/data]
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CTF
    env_file: .env
    command: ['/CTF/docker/app.sh']
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
    driver: local